### ISSUE TITLE
[FEAT]: Implement Backend API for Squeeze Page - Backend

### ISSUE THREAD

**Issue by NgBlaze** [hngprojects/hng_boilerplate_php_laravel_web#28]
### Description:
Develop the API endpoint for the Squeeze Page.

### Purpose:
Provides a backend service that allows us to collect the user email, store it in the database, and send a template to the user.

### Requirements:
- [ ] Develop a RESTful API endpoint to handle POST requests.
- [ ] Validate and verify incoming user data.
- [ ] Store user information securely in the database.
- [ ] Return appropriate response.
- [ ] Handle errors and return appropriate status codes.
- [ ] Send template to a specified email address using an email service (e.g., SendGrid, SMTP).

### Acceptance Criteria:
- The page should be accessible at `/api/v1/squeeze`.
- The endpoint should accept HTTP POST requests.

### Squeeze Form Submission:
**Endpoint:** `POST /api/v1/squeeze`

**Request Body:**
```json
{
  "email": "user@example.com",
  "first_name": "John",
  "last_name": "Doe",
  "phone": "08098761234",
  "location": "Lagos, Nigeria",
  "job_title": "Software Engineer",
  "company": "X-Corp",
  "interests": ["Web Development", "Cloud Computing"],
  "referral_source": "LinkedIn"
```
}

Validation: Ensure all fields are required and the email is in the correct format.

Response (Success):
```json
{
  "message": "Your request has been received. You will get a template shortly."
 ```
}

Response (Error):
```json
{
  "message": "Failed to submit your request",
  "status_code": 400
 ```
}

### Tasks:
- [ ] Create an endpoint (POST /api/v1/squeeze) to handle contact form submissions.
- [ ] Validate user input on the server side.
- [ ] Securely store user information in the database.
- [ ] Implement error handling and return appropriate status codes.
- [ ] Write unit tests for contact form submission and data validation.
- [ ] Write integration tests for confirmation of requests.

### Testing:
- Write unit tests for backend validation and data handling.
- Write integration tests for the end-to-end contact form submission process.
- Perform security testing to ensure data protection and compliance.
- Test various scenarios for form submissions (e.g., successful, invalid data, server errors).

### Expected Outcome
A secure and efficient API endpoint that can receive user email, store it in the database, and confirm the user's request.
The API endpoint allows users to submit a request via the "Squeeze" form, and ensures the template is sent to the appropriate email address.

### Labels
feature
