### ISSUE TITLE
[FEAT] Add Products API - BACKEND

### ISSUE THREAD

**Issue by devMuhammad05** [hngprojects/hng_boilerplate_php_laravel_web#3]
**Description**

Develop an API endpoint to add new products with input validation

**Acceptance Criteria**
- The endpoint should be accessible at  api/products.
- The endpoint should accept HTTP POST requests.
- The endpoint should be secured to ensure that only authenticated users can add new products.
Proper authentication mechanisms (e.g., JWT, OAuth2) should be implemented.
- Requests to the endpoint must include a valid authentication token in the Authorization header. 
```
 Authorization: Bearer <token>
```

- **Request Body**

```
{
  product_name: "Product Name",
  description: "Product Description"
}
```

- **Response**

- On a successful addition of a new product, the API should return a 201 Created status code.
- The response body should contain the newly created product details, including the product ID.

```
{
    "message": "Product created successfully",
    "status_code": 201,
    "data": {
        "product_id": "9c965548-4993-4d52-b6bc-4ef2e5f719e0",
        "name": "Testproduct",
        "description": "Testproduct description"
    }
   }
}
```

- **Validation**

- If any required field is missing or invalid, the API should return a 400 Bad Request status code with appropriate validation error messages.

```
{
  status_code: 400,
  message: ["name must be a string", "description must be a string"],
  error: "Bad Request"
}
```

**Purpose**

Provides a backend service which allows users to add new products to the system

**Requirements**

- Develop server-side logic to add new product
- Securely store product details in the database.
- Ensure compliance with security standards for handling user information.

**Expected Outcome**
- API endpoint allows adding of new products with appropriate validation
 

###Task

- [ ] Create an endpoint POST /api/product to add new product.
- [ ]  Implement server-side logic to handle successful and failed add product request.
- [ ]  Ensure the user has the proper permissions to add product
- [ ]  Write unit tests for the adding new product.
- [ ]  Write integration tests for adding new product.
- [ ]  Perform security testing to ensure data protection and compliance.

###Testing

- Write unit tests for backend validation.
- Write integration tests for the end-to-end add product.
- Perform security testing to ensure data protection and compliance.
- Test various scenarios to adding new product
