### ISSUE TITLE
[FEAT] Implement endpoint to update notification settings

### ISSUE THREAD

**Issue by benjaminharuna1** [hngprojects/hng_boilerplate_php_laravel_web#40]
## Description

Create an endpoint to update user notification settings

## Acceptance Criteria

**Endpoint implementation**:

- The endpoint should be accessible at `/api/v1/notification-settings/{:user_id}`

- The endpoint should only accept HTTP `PATCH` requests

**Endpoint security**:

- Only authenticated users can have access to the endpoint
- A user must have the appropriate permissions to access the endpoint
- Each request to the endpoint must include a valid authentication token in the Authorization header
- `Authorization: Bearer <token>`

**Validation**:

- The endpoint should check whether the provided `user_id` is valid, that is, the `user_id` exists in the database.

  - If the validation fails (user does not exist):
    - send an error response with HTTP status code of `404` (Not Found)
  - If the validation succeeds (user exists):
    - proceed to perform data validation on the request body

- The endpoint should validate the data being sent in the request body
  - the request body should contain at least one of the following keys:
    - `email_notifications`
    - `push_notifications`
    - `sms_notifications`
  - each key only accepts a boolean value `true | false`
  - if the request body contains any unspecified keys or a non-boolean value:
    - send an error response with HTTP status code of `400` (Bad Request)
  - if the request body is successfully validated:
    - retrieve the user notification settings from the database
    - modify the fields specified by the keys in the request body (at least one field can be modified)
    - save the modified user notification settings to the database
    - send a success response with HTTP status code of `200` (OK)

### Sample Request

Route: `PATCH` `/api/v1/notification-settings/{:user_id}`

- Query parameters:

  - `user_id`: UUID string

- **Request Body**:

 ``` 
json
  {
    "push_notifications": true
  }
```  

### Accessing Protected Routes

**Authorization Header**:

- Given a valid token in the Authorization header, the system should allow access and return the requested data when the user accesses a protected route.

``` 
  json
  {
    "Authorization": "Bearer <token>"
  }
  ``` 

- When a request is given without an authorization header or with an invalid token, when the user accesses a protected route, the system should return 401 Unauthorized status.

### Sample Response

- **successful response**

  `user_id` is valid and user notification settings have successfully been updated

``` 
  json
  {
    "status": "success",
    "message": "User notification settings updated successfully",
    "status_code": 200
  }
 ``` 

- **unsuccessful response**

  - `user_id` is invalid and user notification settings cannot be updated

``` 
 json
    {
      "status": "error",
      "message": "User not found",
      "status_code": 404
    }
```     

  - request body contains invalid data

``` 
 json
    {
      "status": "error",
      "message": "Invalid data in the request body",
      "status_code": 400
    }
 ``` 

  - The user is unauthorized and cannot access the endpoint

``` 
    json
    {
      "status": "error",
      "message": "Access denied, Unauthorized request",
      "status_code": 401
    }
```     

### Purpose

The endpoint allows users to manage and update their notification settings

### Requirements

- [x] Ensure an authenticated user is accessing the endpoint
- [x] Ensure that user can only modify their own notification settings
- [x] Develop server-side logic to update the user notification settings
- [x] Ensure that data modification complies with security standards
- [x] Ensure that updated data is stored correctly in the database

### Expected Outcome

A secured API endpoint that enables a user to update their own notification settings

### Tasks

- [x] Implement the endpoint route `/api/v1/notification-settings/{:user_id}`
- [x] Perform the appropriate database operations required to modify user settings and safely store the updates
- [x] Ensure that only authorized users can access the endpoint
- [x] Implement error handling for scenarios when the user is unauthorized and invalid data, with the appropriate HTTP status codes
- [x] Ensure the endpoint returns the appropriate response body

### Testing

- Unit testing for the API endpoint, covering authentication logic, update, error handling etc
- Integration testing to ensure end-to-end functionality.
- Security testing for data protection

**Comment by benjaminharuna1** [comment]
markdown
# Step-by-Step Guide for Setting Up and Testing the PR

## 1. Cloning the Project from GitHub

1. **Clone the Repository**
   
   ```bash
   git clone https://github.com/benjaminharuna1/hng_boilerplate_php_laravel_web.git
   cd {repository}
   ```



## 2. Setting Up the Environment

1. **Install Dependencies**

   ```bash
   composer install
   ```

2. **Set Up the `.env` File**
 ```bash
cp .env.example .env
```

3. **Generate Application Key**

   ```bash
   php artisan key:generate
   ```

4. **Generate JWT Secret Key**

   ```bash
   php artisan jwt:secret
   ```

## 3. Setting Up the Database

1. **Create a Database**

   Create a new database in your MySQL server (or any other database you are using).

2. **Configure Database Connection in `.env`**

   Open the `.env` file and update the database configuration:

   ```env
   DB_CONNECTION=mysql
   DB_HOST=127.0.0.1
   DB_PORT=3306
   DB_DATABASE=your_database_name
   DB_USERNAME=your_database_user
   DB_PASSWORD=your_database_password
   ```

3. **Run Migrations**

   ```bash
   php artisan migrate
   ```

4. **Run Seeders (if any)**

   ```bash
   php artisan db:seed
   ```

## 4. Running the Application

1. **Start the Laravel Development Server**

   ```bash
   php artisan serve
   ```

   The application should now be running at `http://127.0.0.1:8000`.

## 5. Testing the Endpoint

### In the Terminal

```bash
php artisan test
```
If enpoint is successful it should return 
```bash
 PASS  Tests\Feature\NotificationSettingTest
  ✓ user can update notification settings 
```  
### Using Postman

1. **Open Postman** and create a new collection.

2. **Add Environment Variables**:
   - `base_url` for your API base URL.
   - `token` for authentication.

3. **Create a Request for Updating Notification Settings**:
   - Set the request type to `PUT`.
   - Set the URL to `{{base_url}}/api/v1/notification-settings/:user_id`.
   - Set the `Authorization` type to `Bearer Token` and use the `{{token}}` variable.
   - In the `Body` tab, select `raw` and set the type to `JSON`:
     ```json
     {
         "email_notifications": false,
         "sms_notifications": true
     }
     ```

4. **Send the Request** and verify the response.

 **Postman Response**:

   ```json
   {
       "message": "Notification settings updated successfully",
       "data": {
           "user_id": 1,
           "email_notifications": false,
           "sms_notifications": true,
           "profile_id": 1,
           "updated_at": "2024-07-21T13:35:58.000000Z",
           "created_at": "2024-07-21T13:35:58.000000Z"
       }
   }
   ```
