### ISSUE TITLE
[FEAT] API to fetch Single Testimonial  #255

### ISSUE THREAD

**Issue by iotstudent** [hngprojects/hng_boilerplate_php_laravel_web#43]
### Description

Fetch a single testimonial by Id.
### Acceptance Criteria

-    The endpoint should be accessible at GET /api/v1/testimonials/:testimonial_id

-    User should be authenticated to access the endpoint.

-    The endpoint should return a 404 status code if the testimonial does not exist.

-    The endpoint should return a 401 status code if the user is not authenticated.

-    The endpoint should return a 200 status code if the testimonial is fetched.

-    The endpoint should return a single testimonial.

-    The endpoint must accept access token Authorization: Bearer: <token>

### Purpose

Be able to view a single testimonial and leave a comment.

### Requirements

-   Implement API endpoint for single testimonial.

-   Testimonial should be fetched successfully if it exists.

-   Handle unexpected errors and return the appropriate status code.

-   User must be authenticated to access this endpoint.

-   The endpoint must accept access token Authorization: Bearer: <token>

### API Endpoint

     GET /api/v1/testimonials/: testimonial_id

Response

    {
          "message": "Testimonial fetched successfully",
          "status_code": 200,
          "data": {
            "id": "String",
            "author": "String",
            "testimonial": "String",
            "comments": Array, 
            "created_at": "DateTime",
      }
    }

Error Responses

    {
      "status_code": 404,
      "message": "Testimonial not found"
    }
    
    {
      "status_code": 401,
      "message": "Unauthorized "
    }

### Expected Outcome

User should be able to view Single Testimonial and all the comments associated with it.

### Tasks

    

- [ ] Develop API endpoint to view Testimonial.

   

- [ ]  Return proper error cases.

  

- [ ]   Write tests for the API endpoint.

### Testing

-  Unit tests should be written for the API endpoint.

-  Integration tests should be written for the API endpoint.

**Comment by iotstudent** [comment]
slackid: iotstudent 


This issue is linked to an already approved issue [Link](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/255)
